//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_users_table
    {
        public long pk_product_with_user_id { get; set; }
        public long fk_product_id { get; set; }
        public long fk_user_id { get; set; }
        public double price { get; set; }
        public long count { get; set; }
        public double sum { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
